# Generated by Django 4.1.6 on 2023-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='mejor_epoca',
            field=models.CharField(default='', max_length=255),
        ),
    ]
