# Generated by Django 4.1.6 on 2023-05-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_ciudad_mejor_epoca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='mejor_epoca',
        ),
    ]
