# Generated by Django 4.1.6 on 2023-05-08 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestion', '0003_remove_ciudad_mejor_epoca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('viaje_id', models.AutoField(primary_key=True, serialize=False)),
                ('presupuesto', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valoracion', models.FloatField(null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Gestion.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('viajero_id', models.AutoField(primary_key=True, serialize=False)),
                ('creador', models.BooleanField()),
                ('administrador', models.BooleanField()),
                ('viaje_aceptado', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='Viaje.viaje')),
            ],
        ),
    ]
