# Generated by Django 4.1.6 on 2023-05-08 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('relacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('pendiente', models.BooleanField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidos', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
